# @package _group_

ocoqa_small:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa_dpr_format_small.csv

ocoqa:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa_dpr_format.csv

# ocoqa_train_t5_qrecc:
#   _target_: dpr.data.retriever_data.CsvQASrc
#   file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-rewrites-t5-qrecc.csv

# ocoqa_test_t5_qrecc:
#   _target_: dpr.data.retriever_data.CsvQASrc
#   file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-rewrites-t5-qrecc-test.csv

# ocoqa_train_original:
#   _target_: dpr.data.retriever_data.CsvQASrc
#   file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-original.csv

ocoqa_original:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-original.csv

ocoqa_test_original:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-original-test.csv

ocoqa_all_history:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-all-history.csv

ocoqa_test_all_history:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-all-history-test.csv

ocoqa_rewrites_t5_qrecc:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-rewrites-t5-qrecc.csv

ocoqa_test_rewrites_t5_qrecc:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/ocoqa-rewrites-t5-qrecc-test.csv

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/nq-test.csv

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/nq-train.csv

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ${env:SCRATCH}/DPR-data/data/retriever/qas/nq-dev.csv

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test
  
curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test
